flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/reader/MongoSourceReader.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/reader/emitter/MongoRecordEmitter.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/reader/split/MongoScanSourceSplitReader.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/split/MongoScanSourceSplit.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/split/MongoScanSourceSplitState.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/split/MongoSourceSplitSerializer.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/split/MongoSourceSplitState.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/MongoSourceITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/enumerator/MongoSourceEnumStateSerializerTest.java
Exact-once semantics may not be guaranteed at present on partial reads.
We use a number fetchSize to limit the records count for every fetch loop but we didn't record the offset into the split state. When resuming the split reader from a partially completed split, we may re-read some data.
In this PR, we record the current reading offset into split state.
Skip this offset when restoring to prevent duplicate reading.
=> [FLINK-31063] Prevent duplicate reading when restoring from a checkpoint.

flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/sink/MongoSinkITCase.java
Fix the CI fails https://github.com/apache/flink-connector-mongodb/actions/runs/4435527099/jobs/7782784066.
> 2023-03-16T09:46:59.8097110Z 09:46:52,687 [Source: Sequence Source -> Map -> Map -> Sink: Writer (1/1)#7] ERROR org.apache.flink.connector.mongodb.sink.writer.MongoWriter   [] - Bulk Write to MongoDB failed
2023-03-16T09:46:59.8098540Z com.mongodb.MongoBulkWriteException: Bulk write operation error on server localhost:32771. Write errors: [BulkWriteError{index=0, code=11000, message='E11000 duplicate key error collection: test_sink.test-recovery-mongo-sink index: _id_ dup key: { : 1 }', details={}}]. 
We use non-idempotent writes in this test case and may write some data before checkpointed.
In that case we'll meet duplicate write error.
Set `batchIntervalMs` and `batchSize` to -1 …
=> [hotfix] Fix unstable test of MongoSinkITCase.testRecovery

flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/sink/writer/context/DefaultMongoSinkContext.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/sink/writer/context/MongoSinkContext.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/sink/writer/MongoWriterITCase.java, flink-connector-mongodb/src/test/resources/archunit.properties
Fix MongoDB nightly CI failure
https://issues.apache.org/jira/browse/FLINK-31700
> Error:  /home/runner/work/flink-connector-mongodb/flink-connector-mongodb/flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/sink/writer/context/DefaultMongoSinkContext.java:[33,8] org.apache.flink.connector.mongodb.sink.writer.context.DefaultMongoSinkContext is not abstract and does not override abstract method getAttemptNumber() in org.apache.flink.api.connector.sink2.Sink.InitContext
This PR made some changes to make flink-mongodb-connector compatible with both 1.16 and 1.17.
We can build it of flink 1.17 via maven command as follows: 
```shell
mvn clean verify -U -B --no-transfer-progress -Dflink.version=1.17.0 \         
-DaltDeploymentRepository=validation_repository::default::fil …
```
=> [FLINK-31700][Connectors/MongoDB] Fix MongoDB nightly CI failure

.github/workflows/push_pr.yml, pom.xml
There was an issue with ArchUnit version: 1.16.1 uses 0.22.0 whereas 1.17.0 uses 1.0.0. The versions are not compatible so the suggestion is to drop explicit ArchUnit version management from connector and rely on flink-architecture-tests-test dependencies instead.
> Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project flink-connector-cassandra_2.12: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test failed: org.junit.platform.commons.JUnitException: TestEngine with ID 'junit-jupiter' failed to discover tests: org/junit/jupiter/api/io/CleanupMode: org.junit.jupiter.api.io.CleanupMode -> [Help 1]
=> [hotfix] Fix incompatible archunit version

flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/sink/writer/MongoWriter.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/sink/writer/MongoWriterITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/testutils/MongoTestUtil.java
Mongo sink waits for new record to write previous records. I have a upsert-kafka topic filled that has already some events. I start a new upsert-kafka to mongo db sink job. I expect all the data from the topic to be loaded to mongodb right away. But instead, only the first record is written to mongo db. The rest of the records don’t arrive in mongodb until a new event is written to kafka topic. The new event that was written is delayed until the next event arrives. 
To prevent this problem, the MongoWriter should regularly check whether the last write time is over the specific limit.
=> [FLINK-32446][Connectors/MongoDB]  MongoWriter should regularly check whether the last write time is over limit

flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/MongoSourceEnumerator.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/reader/split/MongoScanSourceSplitReader.java
A full run with thread dumps can be found at https://github.com/apache/flink-connector-mongodb/actions/runs/5276796512/jobs/9543998611?pr=10#step:15:48
The root cause of this error is not removing it from `readersAwaitingSplit` when closing an idle reader.
This resulted in splits being incorrectly assigned to readers that did not complete when resuming tasks from checkpoints.
1. `readersAwaitingSplit`: [0]
2. `signalNoMoreSplits` but not remove 0 from `readersAwaitingSplit`
3.  TaskManager failover
4.  split request from reader 1 -> `readersAwaitingSplit`: [0, 1]
5.  but actually assigns split to reader 0.
=> [FLINK-32348][connectors/mongodb] Fix MongoDB tests are flaky and timeout

NOTICE, flink-sql-connector-mongodb/src/main/resources/META-INF/NOTICE
The current copyright year is 2014-2022 in NOTICE files. 
We should change it to 2014-2023.
=> [FLINK-32757][connectors/mongodb][build] Update the copyright with year 2023

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, pom.xml
Backport of https://github.com/apache/flink-connector-mongodb/pull/18
=> [FLINK-33380][connectors/mongodb] Bump Flink version to include 1.18 and 1.19-SNAPSHOT

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, flink-connector-mongodb/pom.xml, pom.xml
After [FLINK-33302](https://issues.apache.org/jira/browse/FLINK-33302) is finished it is now possible to specify jdk version
That allows to add jdk17 and jdk21 support.
=> [FLINK-33899][connectors/mongodb] Java 17 and 21 support for mongodb connector

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, pom.xml
- Add CI support for Flink 1.20-SNAPSHOT.
- Bump flink-connector-parent to 1.1.0 for mongodb connector.
=> [FLINK-34958] Add support Flink 1.20-SNAPSHOT and bump flink-connector-parent to 1.1.0 for mongodb connector

pom.xml
Changes:
-  Bump org.apache.commons:commons-compress from 1.24.0 to 1.26.0 for Flink Mongodb connector
=> [FLINK-35010][connectors/mongodb] Bump org.apache.commons:commons-compress from 1.24.0 to 1.26.1 for Flink Mongodb connector

.github/workflows/push_pr.yml, .github/workflows/weekly.yml
The PR will allow to differentiate between MongoDB connector statistics and others with name ci
=> [FLINK-34961] Use dedicated CI name for MongoDB connector to differentiate it in infra-reports

.github/workflows/push_pr.yml, .github/workflows/weekly.yml
This is a cherry-picked backport of https://github.com/apache/flink-connector-mongodb/pull/33 to v1.1
=> [FLINK-34961][BP v.1.1] Use dedicated CI name for MongoDB connector to differentiate it in infra-reports

docs/content.zh/docs/connectors/table/mongodb.md, docs/content/docs/connectors/table/mongodb.md, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/common/utils/MongoValidationUtils.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactory.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableSink.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoKeyExtractor.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoPrimaryKeyExtractor.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoShardKeysExtractor.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/serialization/MongoRowDataSerializationSchema.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/MongoSourceITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactoryTest.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoPartitionedTableSinkITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoPrimaryKeyExtractorTest.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoShardKeysExtractorTest.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/testutils/MongoTestUtil.java
As [Mongo Reference](https://www.mongodb.com/docs/manual/reference/method/db.collection.update/#upsert-on-a-sharded-collection) says:
> To use db.collection.updateOne() on a sharded collection:
>
> - If you don't specify upsert: true, you must include an exact match on the _id field or target a single shard (such as by including the shard key in the filter).
> - If you specify upsert: true, the filter must include the shard key.
>
> However, documents in a sharded collection can be missing the shard key fields. 
> To target a document that is missing the shard key, you can use the null equality match 
> in conjunction with another filter condition (such as on the _id field).
When upsert into a sharded collection, the value of the shard key needs to be added to the filter. 
For example: …
=> [FLINK-35616][Connectors/MongoDB] Support upsert into sharded collections

flink-sql-connector-mongodb/src/main/resources/META-INF/NOTICE, pom.xml
Bump mongo-driver version from 4.7.2 to 5.1.1 to support MongoDB 7.0
https://www.mongodb.com/docs/drivers/java/sync/current/compatibility/
=> [FLINK-35623] Bump mongo-driver version from 4.7.2 to 5.1.1 to support MongoDB 7.0

docs/content.zh/docs/connectors/table/mongodb.md, docs/content/docs/connectors/table/mongodb.md, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/FilterHandlingPolicy.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoConnectorOptions.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactory.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableSource.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/config/MongoConfiguration.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactoryTest.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableSourceITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoTablePlanTest.java, flink-connector-mongodb/src/test/resources/org/apache/flink/connector/mongodb/table/MongoTablePlanTest.xml
[FLINK-34216][connectors/mongodb] FLIP-377: Support fine-grained configuration to control filter push down for MongoDB Connector
This improvement implements [FLIP-377 Support fine-grained configuration to control filter push down for Table/SQL Sources](https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=276105768)
This FLIP has 2 goals:
- Introduces a new configuration filter.handling.policy to the JDBC and MongoDB connector.
- Suggests a convention option name if other connectors are going to add an option for the same purpose.
=> [FLINK-34216][connectors/mongodb] FLIP-377: Support fine-grained configuration to control filter push down for MongoDB Connector

flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/common/utils/MongoConstants.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/config/MongoReadOptions.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoPaginationSplitter.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoSampleSplitter.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoSingleSplitter.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoSplitVectorSplitter.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoSplitters.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/PartitionStrategy.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoConnectorOptions.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactory.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/config/MongoConfiguration.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/enumerator/MongoSourceEnumStateSerializerTest.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoPaginationSplitterTest.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/enumerator/splitter/MongoSampleSplitterTest.java
This closes FLINK-36075 by:
* Adding new enum value `pagination` for `scan.partition.strategy` option
* Adding `scan.partition.record-size` option to specify the pagination size for each split
Marked it as a draft since more discussion is needed over the API design.
=> [FLINK-36075] Add pagination partitioning strategy

.github/workflows/push_pr.yml, .github/workflows/weekly.yml, docs/data/mongodb.yml, flink-connector-mongodb-e2e-tests/pom.xml, flink-connector-mongodb/pom.xml, flink-sql-connector-mongodb/pom.xml, pom.xml
Drop support for Flink 1.18 and update development version to 2.0-SNAPSHOT
=> [FLINK-35139][Connectors/MongoDB] Drop support for Flink 1.18 and update development version to 2.0-SNAPSHOT

flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/config/MongoReadOptions.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactory.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/MongoSourceITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactoryTest.java
This closes FLINK-37255.
`scan.partition.record-size` option was introduced in FLINK-36075, but corresponding config manifest wasn't updated, which makes it impossible for Flink SQL users to configure it.
=> [FLINK-37255] Fix unable to configure scan.partition.record-size option

flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/source/config/MongoReadOptions.java, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactory.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/source/MongoSourceITCase.java, flink-connector-mongodb/src/test/java/org/apache/flink/connector/mongodb/table/MongoDynamicTableFactoryTest.java
=> [BP-2.0][FLINK-37255] Fix unable to configure scan.partition.record-size option

docs/content.zh/docs/connectors/table/mongodb.md, docs/content/docs/connectors/table/mongodb.md, flink-connector-mongodb/src/main/java/org/apache/flink/connector/mongodb/table/FilterHandlingPolicy.java
- fix lookup.partial-cache.cache-missing-key option name in docs
- Add a missing license header
https://github.com/apache/flink/blob/8dadb73cc45d63d3a8ccfc043158efb71f0916d1/flink-table/flink-table-common/src/main/java/org/apache/flink/table/connector/source/lookup/LookupOptions.java#L69
=> [hotfix][docs] fix option name
